### ISSUE TITLE
Extented Sirius Designer Generator: Type references should be qualified.

### ISSUE THREAD

**Issue by kortef** [occiware/OCCI-Studio#46]
The type references generated for the .odesign file should be qualified using the containing package names, otherwise this might cause type conflicts at runtime. See example below.
Instead of:
![example1](https://user-images.githubusercontent.com/35029901/37706799-0fa115cc-2d01-11e8-8a17-6068b8542641.PNG)
It should be: 
![example2](https://user-images.githubusercontent.com/35029901/37706818-1f1aa112-2d01-11e8-9a7e-5fd15a931e6b.PNG)

**Comment by fzalila** [comment]
I confirm this observation. 
I encountered the same behavior when I have customized the extended LAMP designer.
This behavior appears in MoDMaCAO use-case because we have two different concepts with the same name (Application kind and Application mixin, Component kind and Component mixin).
It will fix this bug in few days.
